//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_Route
    {
        public int ID { get; set; }
        public Nullable<int> FromID { get; set; }
        public Nullable<int> ToID { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
