//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_Driver
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Mobile { get; set; }
        public string IDCard { get; set; }
        public Nullable<int> Status { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> ENG_Listen { get; set; }
        public Nullable<int> ENG_Speak { get; set; }
        public Nullable<int> ENG_Read { get; set; }
        public Nullable<int> ENG_Write { get; set; }
        public Nullable<int> TH_Listen { get; set; }
        public Nullable<int> TH_Speak { get; set; }
        public Nullable<int> TH_Read { get; set; }
        public Nullable<int> TH_Write { get; set; }
        public string Experience { get; set; }
        public Nullable<int> YOS { get; set; }
    }
}
