//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_Passenger
    {
        public int ID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public string Title { get; set; }
        public string FristName { get; set; }
        public string LastName { get; set; }
        public string DOB { get; set; }
    }
}
