//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_AgentPrice
    {
        public int ID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> DiscountP { get; set; }
        public Nullable<decimal> DiscountB { get; set; }
        public Nullable<decimal> Markup { get; set; }
    }
}
