//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_WorkTime
    {
        public int TID { get; set; }
        public Nullable<int> TStart { get; set; }
        public Nullable<int> TEnd { get; set; }
        public string TRemark { get; set; }
        public Nullable<double> Duration { get; set; }
    }
}
