//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_Car
    {
        public int ID { get; set; }
        public string VehicleRegis { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public string Model { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> SitNumber { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
