//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_DriverOfCar
    {
        public int DID { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<System.DateTime> LastJobDate { get; set; }
        public string LastJobTime { get; set; }
        public string LastBooking { get; set; }
    }
}
