//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class synergilimoEntities : DbContext
    {
        public synergilimoEntities()
            : base("name=synergilimoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LMS_Account> LMS_Account { get; set; }
        public DbSet<LMS_AgentPrice> LMS_AgentPrice { get; set; }
        public DbSet<LMS_Car> LMS_Car { get; set; }
        public DbSet<LMS_Driver> LMS_Driver { get; set; }
        public DbSet<LMS_DriverOfCar> LMS_DriverOfCar { get; set; }
        public DbSet<LMS_From> LMS_From { get; set; }
        public DbSet<LMS_Job> LMS_Job { get; set; }
        public DbSet<LMS_Passenger> LMS_Passenger { get; set; }
        public DbSet<LMS_Product> LMS_Product { get; set; }
        public DbSet<LMS_Route> LMS_Route { get; set; }
        public DbSet<LMS_SubAgent> LMS_SubAgent { get; set; }
        public DbSet<LMS_TO> LMS_TO { get; set; }
        public DbSet<LMS_User> LMS_User { get; set; }
        public DbSet<LMS_Vehicle> LMS_Vehicle { get; set; }
        public DbSet<LMS_WorkTime> LMS_WorkTime { get; set; }
        public DbSet<LMS_Booking> LMS_Booking { get; set; }
    }
}
